#!/bin/bash

VERSION=v0.1.1

HOST=127.0.0.1
PORT=8500

function getoptions() {
    shift 1
    while getopts h:p:t:vcw OPT; do
        case $OPT in
            h)
                HOST=$OPTARG;;
            p)
                PORT=$OPTARG;;
            t)
                TEMP_FILE=$OPTARG;;
            c)
                ALERT_STATUS=2;;
            w)
                ALERT_STATUS=1;;
        esac
    done
}

function leader_lost() {
    ALERT_STATUS=2
    getoptions "$@"
    
    curl -s http://$HOST:$PORT/v1/status/leader | egrep -q '^".+"$'

    if [[ $? != 0 ]]; then
        exit $ALERT_STATUS
    fi

    exit 0
}

function leader_changed() {
    TEMP_FILE=/var/tmp/mackerel-agent/consul-leader-changed
    ALERT_STATUS=1
    getoptions "$@"

    LEADER="$(curl -s http://$HOST:$PORT/v1/status/leader)"

    if [[ ! -f $TEMP_FILE ]]; then
        echo "$LEADER" > $TEMP_FILE
    fi

    diff $TEMP_FILE <(echo "$LEADER")

    STATUS=$?

    echo "$LEADER" > $TEMP_FILE

    if [[ $STATUS != "0" ]]; then
        exit $ALERT_STATUS
    fi

    exit 0
}

function server_nodes_changed() {
    TEMP_FILE=/var/tmp/mackerel-agent/consul-server-nodes-changed
    ALERT_STATUS=1
    getoptions "$@"

    PEERS="$(curl -s http://$HOST:$PORT/v1/status/peers)"

    if [[ ! -f $TEMP_FILE ]]; then
        echo "$PEERS" > $TEMP_FILE
    fi

    diff $TEMP_FILE <(echo "$PEERS")

    STATUS=$?

    echo "$PEERS" > $TEMP_FILE

    if [[ $STATUS != "0" ]]; then
        exit $ALERT_STATUS
    fi

    exit 0
}

function version() {
    echo $VERSION
    exit 0
}

function usage() {
    cat <<EOC
usage: check-consul [subcommand] [options]...

check-consul leader-lost [-h host] [-p port] [-w] [-c]
    Description:
        alert when consul leader lost.

    Options:
        -h  consul agent host (default: 127.0.0.1)
        -p  consul agent port (default: 8500)
        -w  set alert level WARNING (exit status 1). (default: not selected)
        -c  set alert level CRITICAL (exit status 2). (default: selected)

check-consul leader-changed [-h host] [-p port] [-t temp_file] [-w] [-c]
    Description:
        alert when consul leader changed.

    Options:
        -h  consul agent host (default: 127.0.0.1)
        -p  consul agent port (default: 8500)
        -t  save previous leader. (default: /var/tmp/mackerel-agent/consul-leader-changed)
        -w  set alert level WARNING (exit status 1). (default: selected)
        -c  set alert level CRITICAL (exit status 2). (default: not selected)

check-consul server-nodes-changed [-h host] [-p port] [-t temp_file] [-w] [-c]
    Description:
        alert when consul server nodes list changed.

    Options:
        -h  consul agent host (default: 127.0.0.1)
        -p  consul agent port (default: 8500)
        -t  save previous server nodes list. (default: /var/tmp/mackerel-agent/consul-server-nodes-changed)
        -w  set alert level WARNING (exit status 1). (default: selected)
        -c  set alert level CRITICAL (exit status 2). (default: not selected)

check-consul version
    Description:
        show version.
EOC
}

case ${1} in
    leader-lost)
        leader_lost "$@";;
    leader-changed)
        leader_changed "$@";;
    server-nodes-changed)
        server_nodes_changed "$@";;
    version)
        version;;
    *)
        usage;;
esac
